# DAC tpl.conf fajl

# konfiguracija za strujne izlaze (DAC_I_OUT)
MOD AO CHANNEL=1, ADDR=0x10, LEDADDR=5704
{
  VREF=2500
  INIT_VAL=2048
}

# konfiguracija za naponske izlaze (DAC_V_OUT)
MOD AO CHANNEL=2, ADDR=0x12, LEDADDR=5706
{
  VREF=2500
  INIT_VAL=2048
}